
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 200
        #连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        #连接池中的最大空闲连接 默认 8
        max-idle: 16
        #连接池中的最小空闲连接 默认 0
        min-idle: 8
redisson:
  address: redis://127.0.0.1:6379
server:
  port: 8081